- name: Install PostgreSQL
  become: true
  apt:
    name:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python3-psycopg2
    update_cache: true

- name: Ensurie the PostgreSQL service is running
  become: true
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create database
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ db.name }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
    state: present

- name: Create user
  become: true
  become_user: postgres
  postgresql_user:
    db: "{{ db.name }}"
    name: "{{ db.user }}"
    password: "{{ db.pass }}"
    priv: ALL
    state: present

- name: Ensure user does not have unnecessary privileges
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ db.user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present
