- name: Download ca.crt to local
  fetch:
    src: ~/registry/certs/ca.crt
    dest: ./ca.crt
    flat: true
  delegate_to: "{{ master }}"

- name: Ensure certs.d exists
  become: true
  file:
    state: directory
    path: /etc/docker/certs.d/{{ master }}:5000

- name: copy registry certificate
  become: true
  copy:
    src: ./ca.crt
    dest: /etc/docker/certs.d/{{ master }}:5000/ca.crt

- name: login docker
  shell: docker login -u {{ registry.user }} -p {{ registry.pass }} {{ master }}:5000

- name: Remove ca.crt from local
  file:
    state: absent
    path: ./ca.crt
  delegate_to: localhost